### ISSUE TITLE
Excess dependencies on Test::Pod et.al 

### ISSUE THREAD

**Issue by kentfredric** [theory/test-file-contents#4]
Firstly, thanks for killing the Pod tests, makes life so much easier for downstream :)

Just looks like you missed the recommended deps, which are now superfluous.

https://github.com/theory/test-file-contents/blob/38534849d0d0d65a5f640d5ceb5b72cfd05c2a53/Build.PL#L18-L25

**Comment by theory** [comment]
Thanks!
